# Generated by Django 3.2.15 on 2022-09-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='book_table',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=50)),
                ('bookimg', models.ImageField(blank=True, null=True, upload_to='img')),
                ('totalbooks', models.IntegerField()),
                ('Available', models.IntegerField()),
                ('issued', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='issued_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_rollno', models.IntegerField()),
                ('stud_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_name', models.CharField(max_length=50)),
                ('bookid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrationapp.book_table')),
            ],
        ),
    ]
