# Generated by Django 3.2.15 on 2022-09-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='bookid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
