# Generated by Django 3.2.15 on 2022-09-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_alter_book_table_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='Available',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book_table',
            name='issued',
            field=models.IntegerField(null=True),
        ),
    ]
